/*
 * ONESPAN SIGN API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.51
 * Contact: support@onespan.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// Package details
    /// </summary>
    [DataContract]
    public partial class ReferencedConditions : IEquatable<ReferencedConditions>
    { 
        /// <summary>
        /// Package Id
        /// </summary>
        /// <value>Package Id</value>

        [DataMember(Name="packageId")]
        public string PackageId { get; set; }

        /// <summary>
        /// Documents
        /// </summary>
        /// <value>Documents</value>

        [DataMember(Name="documents")]
        public List<ReferencedConditionsDocument> Documents { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ReferencedConditions {\n");
            sb.Append("  PackageId: ").Append(PackageId).Append("\n");
            sb.Append("  Documents: ").Append(Documents).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ReferencedConditions)obj);
        }

        /// <summary>
        /// Returns true if ReferencedConditions instances are equal
        /// </summary>
        /// <param name="other">Instance of ReferencedConditions to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReferencedConditions other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    PackageId == other.PackageId ||
                    PackageId != null &&
                    PackageId.Equals(other.PackageId)
                ) && 
                (
                    Documents == other.Documents ||
                    Documents != null &&
                    Documents.SequenceEqual(other.Documents)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (PackageId != null)
                    hashCode = hashCode * 59 + PackageId.GetHashCode();
                    if (Documents != null)
                    hashCode = hashCode * 59 + Documents.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ReferencedConditions left, ReferencedConditions right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ReferencedConditions left, ReferencedConditions right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
