/*
 * ONESPAN SIGN API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.51
 * Contact: support@onespan.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class VirtualRoom : IEquatable<VirtualRoom>
    { 
        /// <summary>
        /// Gets or Sets Video
        /// </summary>

        [DataMember(Name="video")]
        public bool? Video { get; set; }

        /// <summary>
        /// Gets or Sets VideoRecording
        /// </summary>

        [DataMember(Name="videoRecording")]
        public bool? VideoRecording { get; set; }

        /// <summary>
        /// meeting start date and time
        /// </summary>
        /// <value>meeting start date and time</value>

        [DataMember(Name="startDatetime")]
        public DateTime? StartDatetime { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VirtualRoom {\n");
            sb.Append("  Video: ").Append(Video).Append("\n");
            sb.Append("  VideoRecording: ").Append(VideoRecording).Append("\n");
            sb.Append("  StartDatetime: ").Append(StartDatetime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((VirtualRoom)obj);
        }

        /// <summary>
        /// Returns true if VirtualRoom instances are equal
        /// </summary>
        /// <param name="other">Instance of VirtualRoom to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VirtualRoom other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Video == other.Video ||
                    Video != null &&
                    Video.Equals(other.Video)
                ) && 
                (
                    VideoRecording == other.VideoRecording ||
                    VideoRecording != null &&
                    VideoRecording.Equals(other.VideoRecording)
                ) && 
                (
                    StartDatetime == other.StartDatetime ||
                    StartDatetime != null &&
                    StartDatetime.Equals(other.StartDatetime)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Video != null)
                    hashCode = hashCode * 59 + Video.GetHashCode();
                    if (VideoRecording != null)
                    hashCode = hashCode * 59 + VideoRecording.GetHashCode();
                    if (StartDatetime != null)
                    hashCode = hashCode * 59 + StartDatetime.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(VirtualRoom left, VirtualRoom right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(VirtualRoom left, VirtualRoom right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
