/*
 * ONESPAN SIGN API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.51
 * Contact: support@onespan.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;
using IO.Swagger.Security;
using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class AccountSigningLogosApiController : ControllerBase
    { 
        /// <summary>
        /// Retrieves an account&#x27;s Signing Ceremony logos.
        /// </summary>
        /// <remarks>Retrieves an account&#x27;s customized logo for use during the Signing Ceremony. In addition, the corresponding langauge for the account is also retrieved.</remarks>
        /// <response code="200">OK</response>
        /// <response code="401">Not Authorized</response>
        /// <response code="403">Access Denied error</response>
        [HttpGet]
        [Route("/api/account/admin/signingLogos")]
        [Authorize(AuthenticationSchemes = ApiKeyAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("ApiAccountAdminSigningLogosGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(SigningLogos), description: "OK")]
        [SwaggerResponse(statusCode: 401, type: typeof(DefaultError), description: "Not Authorized")]
        [SwaggerResponse(statusCode: 403, type: typeof(DefaultError), description: "Access Denied error")]
        public virtual IActionResult ApiAccountAdminSigningLogosGet()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(SigningLogos));

            //TODO: Uncomment the next line to return response 401 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(401, default(DefaultError));

            //TODO: Uncomment the next line to return response 403 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(403, default(DefaultError));
            string exampleJson = null;
            exampleJson = "[ {\n  \"language\" : \"en\",\n  \"image\" : \"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgA......oziOudIAAAAASUVORK5CYII=\"\n}, {\n  \"language\" : \"fr\",\n  \"image\" : \"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQ......GUjSDJhswDKRpBkw2YH/2Q==\"\n} ]";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<SigningLogos>(exampleJson)
                        : default(SigningLogos);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Add, update or delete Signing Ceremony logos for an account.
        /// </summary>
        /// <remarks>Adds, updates or deletes an account&#x27;s customized Signing Ceremony logos. To add or update a Signing Ceremony logo for a language, pass the Base 64 decoded image (Data URI) with the language. &lt;br&gt; To delete all Singing Ceremony logos, provide empty {} request body. &lt;br&gt; &lt;br&gt; Note that &lt;br&gt; 1. The image has to be one of the following formats - jpeg, png, gif, bmp or svg. &lt;br&gt; 2. The maximum supported size for an image is 1MB &lt;br&gt; 3. The recommended dimensions for a Signing Ceremony logo is 258px X 40 px.</remarks>
        /// <param name="body">The customized Signing Ceremony Logos to be created or updated along with language.</param>
        /// <response code="200">OK</response>
        /// <response code="400">Validation error</response>
        /// <response code="401">Not Authorized</response>
        /// <response code="403">Access Denied error</response>
        [HttpPost]
        [Route("/api/account/admin/signingLogos")]
        [Authorize(AuthenticationSchemes = ApiKeyAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("ApiAccountAdminSigningLogosPost")]
        [SwaggerResponse(statusCode: 400, type: typeof(DefaultError), description: "Validation error")]
        [SwaggerResponse(statusCode: 401, type: typeof(DefaultError), description: "Not Authorized")]
        [SwaggerResponse(statusCode: 403, type: typeof(DefaultError), description: "Access Denied error")]
        public virtual IActionResult ApiAccountAdminSigningLogosPost([FromBody]List<SigningLogo> body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default(DefaultError));

            //TODO: Uncomment the next line to return response 401 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(401, default(DefaultError));

            //TODO: Uncomment the next line to return response 403 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(403, default(DefaultError));

            throw new NotImplementedException();
        }
    }
}
